apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  namespace: microservices
  labels:
    app: payment-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: v1
    spec:
      containers:
      - name: payment-service
        image: ghcr.io/your-org/cryo/payment-service:latest
        ports:
        - containerPort: 3005
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: NODE_ENV
        - name: PORT
          value: "3005"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: POSTGRES_PORT
        - name: POSTGRES_DATABASE
          value: "payment_db"
        - name: POSTGRES_USERNAME
          value: "payment_service"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: POSTGRES_PAYMENT_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: REDIS_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: JWT_SECRET
        - name: PAYMENT_MODE
          value: "simulation"
        - name: PAYMENT_AUTO_APPROVE
          value: "true"
        - name: PAYMENT_SUCCESS_RATE
          value: "0.95"
        - name: ENABLED_PROVIDERS
          value: "sberbank,yandex,tbank"
        - name: USER_SERVICE_URL
          value: "http://user-service:3001"
        - name: GAME_CATALOG_SERVICE_URL
          value: "http://game-catalog-service:3002"
        - name: LIBRARY_SERVICE_URL
          value: "http://library-service:3000"
        - name: SBERBANK_MOCK_API_KEY
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: SBERBANK_MOCK_API_KEY
        - name: YANDEX_MOCK_API_KEY
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: YANDEX_MOCK_API_KEY
        - name: TBANK_MOCK_API_KEY
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: TBANK_MOCK_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
      imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: microservices
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
    name: http
  selector:
    app: payment-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service-hpa
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80