apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
data:
  # Database passwords (base64 encoded)
  # Use: echo -n 'your-password' | base64
  POSTGRES_USER_PASSWORD: dXNlcl9wYXNzd29yZA==  # user_password
  POSTGRES_CATALOG_PASSWORD: Y2F0YWxvZ19wYXNzd29yZA==  # catalog_password
  POSTGRES_LIBRARY_PASSWORD: bGlicmFyeV9wYXNzd29yZA==  # library_password
  POSTGRES_REVIEW_PASSWORD: cmV2aWV3X3Bhc3N3b3Jk  # review_password
  POSTGRES_PAYMENT_PASSWORD: cGF5bWVudF9wYXNzd29yZA==  # payment_password
  POSTGRES_NOTIFICATION_PASSWORD: bm90aWZpY2F0aW9uX3Bhc3N3b3Jk  # notification_password
  POSTGRES_SOCIAL_PASSWORD: c29jaWFsX3Bhc3N3b3Jk  # social_password
  POSTGRES_ACHIEVEMENT_PASSWORD: YWNoaWV2ZW1lbnRfcGFzc3dvcmQ=  # achievement_password
  POSTGRES_SECURITY_PASSWORD: c2VjdXJpdHlfcGFzc3dvcmQ=  # security_password
  POSTGRES_DOWNLOAD_PASSWORD: ZG93bmxvYWRfcGFzc3dvcmQ=  # download_password
  
  # JWT secrets
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # your-jwt-secret-key
  JWT_REFRESH_SECRET: eW91ci1qd3QtcmVmcmVzaC1zZWNyZXQta2V5  # your-jwt-refresh-secret-key
  
  # API keys
  PAYMENT_API_KEY: eW91ci1wYXltZW50LWFwaS1rZXk=  # your-payment-api-key
  EMAIL_API_KEY: eW91ci1lbWFpbC1hcGkta2V5  # your-email-api-key
  
  # Payment provider API keys
  SBERBANK_MOCK_API_KEY: bW9ja19zYmVyYmFua19rZXlfMTIzNDU=  # mock_sberbank_key_12345
  YANDEX_MOCK_API_KEY: bW9ja195bW9uZXlfa2V5XzY3ODkw  # mock_ymoney_key_67890
  TBANK_MOCK_API_KEY: bW9ja190YmFua19rZXlfYWJjZGU=  # mock_tbank_key_abcde
  
  # Redis password (if needed)
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=  # redis_password