global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "social-service-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Social Service metrics
  - job_name: 'social-service'
    static_configs:
      - targets: ['social-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Integration endpoints monitoring
  - job_name: 'social-service-integrations'
    static_configs:
      - targets: ['social-service:3003']
    metrics_path: '/integration/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Health check monitoring
  - job_name: 'social-service-health'
    static_configs:
      - targets: ['social-service:3003']
    metrics_path: '/v1/health/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  # External service dependencies
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'achievement-service'
    static_configs:
      - targets: ['achievement-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'review-service'
    static_configs:
      - targets: ['review-service:3006']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Database monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis monitoring
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Kubernetes monitoring
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name