version: '3.8'

# Docker Compose file for User Service only with its dependencies
# This file runs only the User Service with its database and Redis

services:
  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres-user
      - redis
    env_file:
      - ./user-service/.env.docker
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
    networks:
      - microservices-network
    restart: unless-stopped

  # User Database
  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-user-db
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis_password

# Volumes for data persistence
volumes:
  postgres_user_data:
  redis_data:

# Network for inter-service communication
networks:
  microservices-network:
    driver: bridge