apiVersion: v1
kind: Namespace
metadata:
  name: review-service
  labels:
    app.kubernetes.io/name: review-service
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: gaming-platform