apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: review-service-pdb
  namespace: review-service
  labels:
    app.kubernetes.io/name: review-service
    app.kubernetes.io/component: pdb
    app.kubernetes.io/part-of: gaming-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: review-service
      app.kubernetes.io/component: api