apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: review-service-monitor
  namespace: review-service
  labels:
    app: review-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: review-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  - port: http
    path: /health/detailed
    interval: 60s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'review_service_health_.*'
      targetLabel: __name__
      replacement: '${1}'