apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: review-service
  labels:
    app: review-service
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app: review-service
---
apiVersion: v1
kind: Service
metadata:
  name: review-service-headless
  namespace: review-service
  labels:
    app: review-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app: review-service