apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: user-service
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-headless
  namespace: user-service
  labels:
    app: user-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: user-service