apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: gaming-platform
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: user-service