apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: user-service-vpa
  namespace: microservices
  labels:
    app: user-service
    component: microservice
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service-deployment
  
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 3
  
  resourcePolicy:
    containerPolicies:
    - containerName: user-service
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits