version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: security-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: security_service_test
    ports:
      - "5436:5432"
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    networks:
      - security-test-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    container_name: security-redis-test
    ports:
      - "6382:6379"
    networks:
      - security-test-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgdata-test:

networks:
  security-test-net:
    driver: bridge