apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: security-service-pdb
  labels:
    app: security-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: security-service