apiVersion: v1
kind: Secret
metadata:
  name: security-service-secret
  labels:
    app: security-service
type: Opaque
stringData:
  # Database Credentials
  DB_PASSWORD: "postgres"
  
  # JWT Configuration
  JWT_SECRET: "change-me-in-production-use-strong-secret"
  JWT_EXPIRES_IN: "24h"
  
  # Redis Password (if using authentication)
  REDIS_PASSWORD: ""
  
  # Kafka SASL Configuration (if using)
  KAFKA_USERNAME: ""
  KAFKA_PASSWORD: ""
  
  # External API Keys (if needed)
  EXTERNAL_API_KEY: ""
  
  # Encryption Keys for sensitive data
  ENCRYPTION_KEY: "change-me-in-production-32-char-key"

