apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  PORT: "3000"
  CORS_ORIGIN: "*" # Should be more specific in a real production environment
  # Database connection
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  DB_USERNAME: "user"
  DB_PASSWORD: "password"
  DB_DATABASE: "notification_db"
  # Redis connection
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  # Service URLs
  USER_SERVICE_URL: "http://user-service:3000"
  # Mailer settings
  MAILER_URL: "https://api.examplemailer.com/send" # Placeholder
  MAILER_API_KEY: "your-api-key" # Should be a secret
  MAILER_FROM_EMAIL: "noreply@myplatform.com"
