apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  labels:
    app: notification-service
    component: backend
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # Use: echo -n "your-secret" | base64
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS10aGF0LWlzLWF0LWxlYXN0LTMyLWNoYXJhY3RlcnMtbG9uZw==
  DB_USERNAME: dXNlcg==
  DB_PASSWORD: cGFzc3dvcmQ=
  REDIS_PASSWORD: ""
  EMAIL_API_KEY: eW91ci1tYWlscnUtYXBpLWtleQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-tls
  labels:
    app: notification-service
    component: backend
type: kubernetes.io/tls
data:
  # TLS certificate and key for HTTPS (if needed)
  # tls.crt: <base64-encoded-certificate>
  # tls.key: <base64-encoded-private-key>