apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
  labels:
    app: payment-service
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: payment-service