version: '3.8'

services:
  # Test Database - isolated from dev/prod
  postgres-test:
    image: postgres:14-alpine
    container_name: notification-postgres-test
    environment:
      - POSTGRES_USER=notification_test_user
      - POSTGRES_PASSWORD=notification_test_password
      - POSTGRES_DB=notification_test_db
    ports:
      - "5437:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    tmpfs:
      - /var/lib/postgresql/data  # Use tmpfs for faster tests
    command: >
      postgres
      -c shared_preload_libraries=''
      -c max_connections=100
      -c shared_buffers=128MB
      -c effective_cache_size=256MB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_worker_processes=8
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=8
      -c max_parallel_maintenance_workers=4

  # Test Redis - isolated from dev/prod
  redis-test:
    image: redis:7-alpine
    container_name: notification-redis-test
    ports:
      - "6381:6379"  # Different port to avoid conflicts
    volumes:
      - redis_test_data:/data
    command: >
      redis-server
      --appendonly no
      --save ""
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    tmpfs:
      - /data  # Use tmpfs for faster tests

  # Test Email Mock Server (for integration testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: notification-mailhog-test
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      - MH_STORAGE=memory
      - MH_HOSTNAME=mailhog

volumes:
  postgres_test_data:
  redis_test_data:

networks:
  default:
    name: notification-test-network