version: '3.8'

services:
  # Notification Service
  notification-service:
    build:
      context: .
      target: development
    container_name: notification-service
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=notification_user
      - DB_PASSWORD=notification_password
      - DB_DATABASE=notification_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - notification-network

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: notification-postgres
    environment:
      - POSTGRES_USER=notification_user
      - POSTGRES_PASSWORD=notification_password
      - POSTGRES_DB=notification_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - notification-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - notification-network

  # PostgreSQL Admin (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: notification-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@notification.local
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    networks:
      - notification-network

volumes:
  postgres_data:
  redis_data:

networks:
  notification-network:
    driver: bridge
