version: '3.8'

services:
  # Development Database and Cache only
  postgres:
    image: postgres:14-alpine
    container_name: notification-postgres-dev
    environment:
      - POSTGRES_USER=notification_user
      - POSTGRES_PASSWORD=notification_password
      - POSTGRES_DB=notification_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7-alpine
    container_name: notification-redis-dev
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_dev_data:
  redis_dev_data: