version: '3.8'

services:
  review-service:
    build:
      context: .
      target: production
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=review_user
      - DATABASE_PASSWORD=review_password
      - DATABASE_NAME=review_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - review-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=review_user
      - POSTGRES_PASSWORD=review_password
      - POSTGRES_DB=review_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - review-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - review-network

volumes:
  postgres_data:
  redis_data:

networks:
  review-network:
    driver: bridge