apiVersion: v1
kind: ConfigMap
metadata:
  name: library-service-config
  labels:
    app: library-service
    component: backend
data:
  # Application Configuration
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  
  # Database Configuration (non-sensitive)
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "library_service"
  DATABASE_POOL_SIZE: "10"
  DATABASE_CONNECTION_TIMEOUT: "30000"
  DATABASE_IDLE_TIMEOUT: "10000"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_CONNECT_TIMEOUT: "5000"
  REDIS_COMMAND_TIMEOUT: "3000"
  
  # Cache Configuration
  CACHE_TTL: "300"
  CACHE_MAX_ITEMS: "1000"
  
  # External Services URLs
  GAME_CATALOG_SERVICE_URL: "http://game-catalog-service"
  USER_SERVICE_URL: "http://user-service"
  PAYMENT_SERVICE_URL: "http://payment-service"
  
  # API Configuration
  API_RATE_LIMIT: "100"
  API_RATE_WINDOW: "60000"
  
  # Health Check Configuration
  HEALTH_CHECK_TIMEOUT: "5000"
  
  # Monitoring Configuration
  METRICS_ENABLED: "true"
  METRICS_PATH: "/metrics"
  
  # Performance Configuration
  MAX_CONCURRENT_REQUESTS: "1000"
  REQUEST_TIMEOUT: "30000"
