apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: library-service-pdb
  labels:
    app: library-service
    component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: library-service