apiVersion: v1
kind: ServiceAccount
metadata:
  name: library-service
  labels:
    app: library-service
    component: backend
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: library-service-role
  labels:
    app: library-service
    component: backend
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: library-service-rolebinding
  labels:
    app: library-service
    component: backend
subjects:
- kind: ServiceAccount
  name: library-service
  namespace: default # Adjust namespace as needed
roleRef:
  kind: Role
  name: library-service-role
  apiGroup: rbac.authorization.k8s.io