# Development environment values
replicaCount: 1

image:
  repository: your-registry/security-service
  tag: "latest"
  pullPolicy: Always

# Disable autoscaling in development
autoscaling:
  enabled: false

# Disable network policy in development for easier debugging
networkPolicy:
  enabled: false

# Disable pod disruption budget in development
podDisruptionBudget:
  enabled: false

# Development environment variables
env:
  NODE_ENV: development
  LOG_LEVEL: debug
  DB_SYNCHRONIZE: "true"
  DB_LOGGING: "true"
  
  # Development database
  DB_HOST: postgres-dev
  DB_NAME: security_service_dev
  
  # Development Redis
  REDIS_HOST: redis-dev
  
  # Relaxed security thresholds for development
  SECURITY_LOGIN_PER_MINUTE_IP: "100"
  SECURITY_LOGIN_PER_MINUTE_USER: "50"
  SECURITY_TXN_PER_MINUTE_USER: "50"
  
  # Development CORS - allow all origins
  CORS_ORIGINS: "*"

# Development secrets (not for production!)
secrets:
  DB_PASSWORD: devpassword
  JWT_SECRET: dev-jwt-secret-not-for-production
  REDIS_PASSWORD: ""

# Lower resource requirements for development
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

# More frequent health checks for development
healthChecks:
  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
  readinessProbe:
    initialDelaySeconds: 3
    periodSeconds: 3
  startupProbe:
    initialDelaySeconds: 2
    periodSeconds: 2
    failureThreshold: 10