apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "security-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "security-service.name" . }}
    helm.sh/chart: {{ include "security-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $k, $v := .Values.env }}
  {{ $k }}: "{{ $v }}"
{{- end }}

