{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "security-service.fullname" . }}
  labels:
    {{- include "security-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "security-service.selectorLabels" . | nindent 6 }}
  policyTypes:
  {{- if .Values.networkPolicy.ingress.enabled }}
  - Ingress
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  - Egress
  {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
  - from:
    {{- with .Values.networkPolicy.ingress.from }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
  {{- with .Values.networkPolicy.egress.to }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  # Allow HTTPS outbound
  - to: []
    ports:
    - protocol: TCP
      port: 443
  {{- end }}
{{- end }}