apiVersion: v1
kind: Secret
metadata:
  name: {{ include "security-service.fullname" . }}
  labels:
    {{- include "security-service.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

