# =============================================================================
# Horizontal Pod Autoscaler for Auth Service
# Automatic scaling based on CPU, memory, and custom metrics
# =============================================================================

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
  namespace: gaming-platform
  labels:
    app: auth-service
    tier: backend
    component: authentication
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  
  minReplicas: 3
  maxReplicas: 20
  
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Custom metrics (if Prometheus adapter is configured)
  - type: Pods
    pods:
      metric:
        name: auth_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  
  - type: Pods
    pods:
      metric:
        name: auth_response_time_p95
      target:
        type: AverageValue
        averageValue: "500m"  # 500ms
  
  # Scaling behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    
    scaleUp:
      stabilizationWindowSeconds: 60   # 1 minute
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max

---
# =============================================================================
# Vertical Pod Autoscaler (VPA) - Optional
# Automatic resource request/limit adjustment
# =============================================================================

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: auth-service-vpa
  namespace: gaming-platform
  labels:
    app: auth-service
    tier: backend
    component: authentication
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  
  updatePolicy:
    updateMode: "Auto"  # Can be "Off", "Initial", or "Auto"
  
  resourcePolicy:
    containerPolicies:
    - containerName: auth-service
      minAllowed:
        cpu: 100m
        memory: 256Mi
      maxAllowed:
        cpu: 2000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits