apiVersion: v1
kind: ConfigMap
metadata:
  name: achievement-config
  labels:
    app: achievement-service
data:
  NODE_ENV: "production"
  PORT: "3003"
  DATABASE_PORT: "5432"
  DATABASE_SSL: "false"
  DATABASE_SYNCHRONIZE: "false"
  DATABASE_LOGGING: "false"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_TTL: "3600"
  JWT_EXPIRES_IN: "24h"
  CORS_ORIGIN: "https://your-production-domain.com"
  LOG_LEVEL: "info"
  HEALTH_CHECK_TIMEOUT: "5000"
  RATE_LIMIT_TTL: "60"
  RATE_LIMIT_LIMIT: "100"
  CACHE_TTL: "300"
  CACHE_MAX: "1000"