export enum SecurityEventType {
  LOGIN = 'LOGIN',
  TRANSACTION = 'TRANSACTION',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  IP_BLOCK = 'IP_BLOCK',
  ACCOUNT_LOCK = 'ACCOUNT_LOCK',
  PASSWORD_RESET = 'PASSWORD_RESET',
  OTHER = 'OTHER',
}

