export enum SecurityAlertType {
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  MULTIPLE_FAILED_LOGINS = 'MULTIPLE_FAILED_LOGINS',
  POSSIBLE_FRAUD = 'POSSIBLE_FRAUD',
  IP_BLOCKED = 'IP_BLOCKED',
  OTHER = 'OTHER',
}

