groups:
  - name: security-service.rules
    rules:
      - record: job:security_checks_rate:5m
        expr: rate(security_checks_total[5m])

      - alert: SecurityHighErrorRate
        expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) by (job) > 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High 5xx rate on security-service"
          description: ">10% requests failing with 5xx for 10m"

      - alert: SecurityHighRiskEventsSpike
        expr: rate(high_risk_events_total[10m]) > 5
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Spike in high risk events"
          description: "High risk events growing fast (>5/10m)"

      - alert: ManyActiveAlerts
        expr: security_active_alerts > 20
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Many active (unresolved) alerts"
          description: "> 20 active alerts for 15m"

