version: '3.8'

services:
  test-postgres:
    image: postgres:15-alpine
    container_name: achievement-service-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: achievement_service_test
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-redis:
    image: redis:7-alpine
    container_name: achievement-service-test-redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass ""

volumes:
  test_postgres_data: