version: '3.8'

services:
  library-service:
    build:
      context: .
      target: dependencies
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3004:3000" # Exposing on 3004 as per integration map convention
    command: npm run start:dev
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=library_service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GAMES_CATALOG_SERVICE_URL=http://mock-game-catalog:3001
      - USER_SERVICE_URL=http://mock-user-service:3003

  postgres:
    image: postgres:14-alpine
    ports:
      - "5436:5432" # Use a different host port to avoid conflicts
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379" # Use a different host port

  # Mock services for dependencies
  mock-game-catalog:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./mocks/game-catalog/default.conf:/etc/nginx/conf.d/default.conf
      - ./mocks/game-catalog/data:/usr/share/nginx/html

  mock-user-service:
    image: nginx:alpine
    ports:
      - "3003:80"
    volumes:
      - ./mocks/user-service/default.conf:/etc/nginx/conf.d/default.conf
      - ./mocks/user-service/data:/usr/share/nginx/html

volumes:
  postgres_data:
