apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: download-service-pdb
  labels:
    app: download-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: download-service