apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: download-service-monitor
  labels:
    app: download-service
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: download-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'go_.*'
      action: drop
    - sourceLabels: [__name__]
      regex: 'promhttp_.*'
      action: drop