apiVersion: v1
kind: ConfigMap
metadata:
  name: library-service-config
data:
  LOG_LEVEL: "warn"
  DATABASE_POOL_SIZE: "20"
  CACHE_TTL: "600"
  API_RATE_LIMIT: "100"
  MAX_CONCURRENT_REQUESTS: "2000"