apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-service
spec:
  template:
    spec:
      containers:
      - name: library-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: LOG_LEVEL
          value: "debug"