# =============================================================================
# Docker Compose Override for Auth Service
# Enhanced security and container orchestration configuration
# =============================================================================

version: '3.8'

services:
  auth-service:
    # Security configurations
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem for security
    read_only: true
    
    # Temporary filesystems for writable directories
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/logs:noexec,nosuid,size=50m
    
    # Resource limits for container orchestration
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G
          pids: 100
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Enhanced health check configuration
    healthcheck:
      test: ["CMD", "node", "health-check.js", "--endpoint", "/api/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy for production
    restart: unless-stopped
    
    # Additional environment variables for security
    environment:
      # Security settings
      - NODE_OPTIONS=--max-old-space-size=768
      - UV_THREADPOOL_SIZE=4
      
      # Health check configuration
      - HEALTH_CHECK_TIMEOUT=5000
      - HEALTH_CHECK_RETRIES=2
      - HEALTH_CHECK_SILENT=true
      
      # Container security
      - NODE_ENV=production
      - NPM_CONFIG_AUDIT=false
      - NPM_CONFIG_FUND=false
      - NPM_CONFIG_UPDATE_NOTIFIER=false
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=auth-service"
    
    # Labels for container orchestration
    labels:
      - "service.name=auth-service"
      - "service.version=1.0.0"
      - "service.type=microservice"
      - "service.tier=backend"
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=PathPrefix(`/api/auth`)"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3001"
      - "traefik.http.routers.auth-service.middlewares=auth-ratelimit"
      - "traefik.http.middlewares.auth-ratelimit.ratelimit.burst=100"

# =============================================================================
# Security Features:
# 
# 1. no-new-privileges: Prevents privilege escalation
# 2. read_only: Read-only root filesystem
# 3. tmpfs: Temporary filesystems for writable directories
# 4. Resource limits: CPU, memory, and PID limits
# 5. Enhanced health checks with proper timeouts
# 6. Structured logging with rotation
# 7. Container labels for orchestration
# 8. Node.js security optimizations
# 9. Restart policy for high availability
# 10. Traefik integration for load balancing
# =============================================================================