groups:
  - name: payment-service.rules
    interval: 30s
    rules:
      - alert: PaymentErrorRateHigh
        expr: sum(rate(payments_total{status!="COMPLETED"}[5m])) / sum(rate(payments_total[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Payment failure rate is elevated"
          description: "More than 5% of payments are failing in the last 5 minutes."
      - alert: PaymentProcessingSlow
        expr: histogram_quantile(0.95, sum(rate(payment_duration_seconds_bucket[5m])) by (le)) > 2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Payment processing latency is high"
          description: "95th percentile payment processing time is above 2s."
