version: '3.8'

# Local docker-compose file for user-service development
# This file sets up only the user-service with its dedicated dependencies
# Use this for isolated development of user-service

services:
  # User Service Application
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-local
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.local
    networks:
      - user-service-network
    restart: unless-stopped

  # PostgreSQL Database (dedicated for user-service)
  postgres:
    image: postgres:15-alpine
    container_name: user-service-postgres-local
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-user_service_db}
    ports:
      - "5433:5432"  # Different external port to avoid conflicts
    volumes:
      - user-service-postgres-data:/var/lib/postgresql/data
    networks:
      - user-service-network
    restart: unless-stopped

  # Redis Cache (dedicated for user-service)
  redis:
    image: redis:7-alpine
    container_name: user-service-redis-local
    ports:
      - "6380:6379"  # Different external port to avoid conflicts
    volumes:
      - user-service-redis-data:/data
    networks:
      - user-service-network
    restart: unless-stopped
    command: redis-server --appendonly yes

# Volumes for data persistence
volumes:
  user-service-postgres-data:
  user-service-redis-data:

# Network for inter-service communication
networks:
  user-service-network:
    driver: bridge