apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cryo
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml

