groups:
  - name: library-service-alerts
    rules:
      # High-level service availability
      - alert: LibraryServiceDown
        expr: up{job="library-service"} == 0
        for: 1m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Library Service is down"
          description: "Library Service has been down for more than 1 minute"

      # HTTP Error Rates
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      - alert: CriticalErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.10
        for: 1m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Critical error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      # Response Time Alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 3m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for the last 5 minutes"

      - alert: CriticalResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 3
        for: 1m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Critical response time detected"
          description: "95th percentile response time is {{ $value }}s for the last 5 minutes"

      # Memory Usage Alerts
      - alert: HighMemoryUsage
        expr: (nodejs_heap_size_used_bytes / nodejs_heap_size_total_bytes) > 0.8
        for: 5m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} for the last 5 minutes"

      - alert: CriticalMemoryUsage
        expr: (nodejs_heap_size_used_bytes / nodejs_heap_size_total_bytes) > 0.9
        for: 2m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} for the last 2 minutes"

      # Event Loop Lag
      - alert: HighEventLoopLag
        expr: nodejs_eventloop_lag_seconds > 0.1
        for: 3m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High event loop lag detected"
          description: "Event loop lag is {{ $value }}s for the last 3 minutes"

      - alert: CriticalEventLoopLag
        expr: nodejs_eventloop_lag_seconds > 0.2
        for: 1m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Critical event loop lag detected"
          description: "Event loop lag is {{ $value }}s for the last minute"

      # Database Connection Alerts
      - alert: DatabaseConnectionFailure
        expr: database_connections_active == 0
        for: 1m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Database connection failure"
          description: "No active database connections for the last minute"

      - alert: HighDatabaseConnections
        expr: database_connections_active > database_connections_max * 0.8
        for: 5m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High database connection usage"
          description: "Database connection usage is {{ $value }} out of {{ database_connections_max }}"

      # Redis Connection Alerts
      - alert: RedisConnectionFailure
        expr: redis_connected_clients == 0
        for: 1m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Redis connection failure"
          description: "No Redis connections for the last minute"

      # Business Logic Alerts
      - alert: HighLibrarySearchFailureRate
        expr: rate(library_search_errors_total[5m]) / rate(library_search_requests_total[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High library search failure rate"
          description: "Library search failure rate is {{ $value | humanizePercentage }}"

      - alert: HighPurchaseProcessingFailureRate
        expr: rate(purchase_processing_errors_total[5m]) / rate(purchase_processing_requests_total[5m]) > 0.02
        for: 2m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "High purchase processing failure rate"
          description: "Purchase processing failure rate is {{ $value | humanizePercentage }}"

      # Cache Performance
      - alert: LowCacheHitRate
        expr: cache_hit_rate < 0.7
        for: 10m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} for the last 10 minutes"

      - alert: CriticalCacheHitRate
        expr: cache_hit_rate < 0.5
        for: 5m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Critical cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      # External Service Dependencies
      - alert: ExternalServiceDown
        expr: external_service_status{service=~"game-catalog|payment|user"} == 0
        for: 2m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "External service {{ $labels.service }} is down"
          description: "External service {{ $labels.service }} has been down for more than 2 minutes"

      - alert: HighExternalServiceErrorRate
        expr: rate(external_service_errors_total[5m]) / rate(external_service_requests_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High external service error rate"
          description: "External service {{ $labels.service }} error rate is {{ $value | humanizePercentage }}"

      # Health Check Alerts
      - alert: HealthCheckFailure
        expr: health_check_status{check_type!="external"} == 0
        for: 1m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Health check failure"
          description: "Health check {{ $labels.check_type }} has been failing for more than 1 minute"

      - alert: ProductionReadinessFailure
        expr: production_readiness_status == 0
        for: 30s
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Production readiness check failure"
          description: "Production readiness check has been failing for more than 30 seconds"

      # Performance Degradation
      - alert: PerformanceDegradation
        expr: |
          (
            (nodejs_heap_size_used_bytes / nodejs_heap_size_total_bytes) > 0.8 or
            nodejs_eventloop_lag_seconds > 0.1 or
            histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
          )
        for: 5m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "Performance degradation detected"
          description: "Multiple performance indicators show degradation"

      # Security Alerts
      - alert: SecurityCheckFailure
        expr: security_check_status == 0
        for: 1m
        labels:
          severity: critical
          service: library-service
        annotations:
          summary: "Security check failure"
          description: "Security health check has been failing for more than 1 minute"

      - alert: WeakSecretsDetected
        expr: weak_secrets_count > 0
        for: 0s
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "Weak secrets detected"
          description: "{{ $value }} weak secrets detected in the system"

      # Resource Exhaustion
      - alert: HighActiveHandles
        expr: nodejs_active_handles > 1000
        for: 5m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High number of active handles"
          description: "Active handles count is {{ $value }}, possible resource leak"

      - alert: HighGCDuration
        expr: nodejs_gc_duration_seconds > 0.1
        for: 3m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High garbage collection duration"
          description: "GC duration is {{ $value }}s, indicating memory pressure"

  - name: library-service-business-alerts
    rules:
      # Business Metrics Alerts
      - alert: UnusualLibraryActivity
        expr: |
          (
            rate(library_games_added_total[1h]) > (
              avg_over_time(rate(library_games_added_total[1h])[7d:1h]) * 3
            )
          ) or (
            rate(library_games_removed_total[1h]) > (
              avg_over_time(rate(library_games_removed_total[1h])[7d:1h]) * 3
            )
          )
        for: 10m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "Unusual library activity detected"
          description: "Library activity is significantly higher than normal"

      - alert: HighSearchLatency
        expr: histogram_quantile(0.95, rate(library_search_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "High library search latency"
          description: "95th percentile search latency is {{ $value }}s"

      - alert: LowSearchSuccessRate
        expr: rate(library_search_success_total[5m]) / rate(library_search_requests_total[5m]) < 0.95
        for: 5m
        labels:
          severity: warning
          service: library-service
        annotations:
          summary: "Low search success rate"
          description: "Search success rate is {{ $value | humanizePercentage }}"